1

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -4,13 +4,13 @@ jobs:
     docker:
       # using custom image, see .circleci/images/primary/Dockerfile
       - image: circleci/python:3.5-stretch-browsers
-      - image: postgres:9.4.1
-        name: dbtest
-        ports: 5432
-        environment:
-          POSTGRES_USER: testdb
-          POSTGRES_PASSWORD: testdb
-          POSTGRES_DB: testdb
+      # - image: postgres:9.4.1
+      #   name: dbtest
+      #   ports: 5432
+      #   environment:
+      #     POSTGRES_USER: testdb
+      #     POSTGRES_PASSWORD: testdb
+      #     POSTGRES_DB: testdb
     working_directory: ~/anhnguyen/circleci-example
 
     environment:
@@ -21,18 +21,18 @@ jobs:
     steps:
       - checkout
 
-      - run:
-          name: Waiting for Postgres to be ready
-          command: |
-            for i in `seq 1 10`;
-            do
-              nc -z dbtest 5432 && echo Success && exit 0
-              echo -n .
-              sleep 1
-            done
-            echo Failed waiting for Postgress && exit 1
+      # - run:
+      #     name: Waiting for Postgres to be ready
+      #     command: |
+      #       for i in `seq 1 10`;
+      #       do
+      #         nc -z dbtest 5432 && echo Success && exit 0
+      #         echo -n .
+      #         sleep 1
+      #       done
+      #       echo Failed waiting for Postgress && exit 1
 
-      - run: mkdir -p $TEST_RESULTS
+      # - run: mkdir -p $TEST_RESULTS
 
       - setup_remote_docker
 
@@ -45,6 +45,9 @@ jobs:
       #     environment:
       #       DATABASE_URL: "postgres://testdb@127.0.0.1:5432/testdb?sslmode=disable"
       #     command: ./docker/test/test.sh
+      - run:
+          name: Run Postgres container
+          command: docker run -e POSTGRES_USER='testdb' -e POSTGRES_DB='testdb' -e POSTGRES_PASSWORD='testdb' -e POSTGRES_HOST=127.0.0.1 -e POSTGRES_HOST=127.0.0.1 --name dbtest -p 5432:5432 postgres:9.5-alpine
 
       - run:
           name: Build and push Docker image
