1

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,95 +1,73 @@
 version: 2
 jobs:
   build:
-    working_directory: ~/anhnguyen/api-app
-    parallelism: 1
-    shell: /bin/bash --login
-    environment:
-      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
-      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
-      GROUP: django_ci_anhnguyen
-      REPO: api-app
     docker:
-    - image: circleci/python:3.5-stretch-browsers
-    - image: circleci/postgres:9.6-alpine-ram
-      environment:
-        POSTGRES_USER: ubuntu
-        POSTGRES_DB: testdb
+      # using custom image, see .circleci/images/primary/Dockerfile
+      - image: circleci/cci-demo-docker-primary:0.0.2
+      - image: postgres:9.4.1
+        environment:
+          POSTGRES_USER: ubuntu
+          POSTGRES_DB: contacts
+    working_directory: /go/src/github.com/circleci/cci-demo-docker
+
+    environment:
+      TEST_RESULTS: /tmp/test-results
+
     steps:
-    - checkout
+      - checkout
 
-    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
+      - run:
+          name: Waiting for Postgres to be ready
+          command: |
+            for i in `seq 1 10`;
+            do
+              nc -z localhost 5432 && echo Success && exit 0
+              echo -n .
+              sleep 1
+            done
+            echo Failed waiting for Postgress && exit 1
 
-    - restore_cache:
-        keys:
-        # This branch if available
-        - v1-dep-{{ .Branch }}-
-        # Default branch if not
-        - v1-dep-develop-
-        # Any branch if there are none on the default branch - this should be unnecessary if you have your default branch configured correctly
-        - v1-dep-
-    # This is based on your 1.0 configuration file or project settings
-    - setup_remote_docker
-    - run: set -e
-    - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
-    - run:
-        name: Build Image
-        command: ./docker/bin/build.sh
+      - run: mkdir -p $TEST_RESULTS
 
-    - run:
-        name: Run Test
-        command: echo "Test"
-        command: ./docker/test/test.sh
-    # Save dependency cache
-    - save_cache:
-        key: v1-dep-{{ .Branch }}-{{ epoch }}
-        paths:
-        # This is a broad list of cache paths to include many possible development environments
-        # You can probably delete some of these entries
-        - vendor/bundle
-        - ~/virtualenvs
-        - ~/.m2
-        - ~/.ivy2
-        - ~/.bundle
-        - ~/.go_workspace
-        - ~/.gradle
-        - ~/.cache/bower
-    # Test
-    #   This would typically be a build job when using workflows, possibly combined with build
-    # This is based on your 1.0 configuration file or project settings
-    # - run: ./docker/test/test.sh
-    # Deployment
-    # Your existing circle.yml file contains deployment steps.
-    # The config translation tool does not support translating deployment steps
-    # since deployment in CircleCI 2.0 are better handled through workflows.
-    # See the documentation for more information https://circleci.com/docs/2.0/workflows/
-    # Teardown
-    #   If you break your build into multiple jobs with workflows, you will probably want to do the parts of this that are relevant in each
-    # Save test results
-    - store_test_results:
-        path: /tmp/circleci-test-results
-    # Save artifacts
-    - store_artifacts:
-        path: /tmp/circleci-artifacts
-    - store_artifacts:
-        path: /tmp/circleci-test-results
-  # test:
-  #   docker:
-  #     - image: circleci/postgres:9.6-alpine-ram
-  #   steps:
-  #   - checkout
-  #   - setup_remote_docker
-  #   - run: set -e
-  #   - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
-  #   - run:
-  #       name: Test
-  #       command: echo "Test"
-  #       command: ./docker/test/test.sh
-workflows:
-  version: 2
-  build_and_test:
-    jobs:
-      - build
-      # - test:
-      #     requires:
-      #       - build
+      - run:
+          name: Run unit tests
+          environment:
+            DATABASE_URL: "postgres://ubuntu@localhost:5432/contacts?sslmode=disable"
+            DB_MIGRATIONS: /go/src/github.com/circleci/cci-demo-docker/db/migrations
+          command: |
+            set -ou pipefail
+            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
+            # Notice this `set -o pipefail`, this will cause script to fail if `make test` fails
+            # without this option script will return success regardless of testing result due to pipe after test command
+            make test | tee ${TEST_RESULTS}/go-test.out
+
+      - setup_remote_docker
+
+      # This should go into custom primary image, here's only for the sake of explanation
+      - run:
+          name: Install Docker client
+          command: |
+            set -x
+            VER="17.03.0-ce"
+            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
+            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
+            mv /tmp/docker/* /usr/bin
+
+      - run:
+          name: Build service
+          command: make
+
+      - run:
+          name: Build and push Docker image
+          command: |
+            TAG="0.1.${CIRCLE_BUILD_NUM}"
+            docker build -t circleci/cci-demo-docker:$TAG .
+            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
+            docker push circleci/cci-demo-docker:$TAG
+
+      - store_artifacts:
+          path: /tmp/test-results
+          destination: raw-test-output
+
+      - store_test_results:
+          path: /tmp/test-results
